### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_fileformat#29]
When a HTTP proxy is needed, conversion from PAGE to ALTO is failing:

~~~
# ocrd-fileformat-transform -I OCR-D-GT-PAGE -O ALTO
14:36:13.086 INFO ocrd-fileformat-transform - page --> alto: input file OCR-D-GT-PAGE_00000024 (PHYS_0024)
java.net.ConnectException: Connection timed out (Connection timed out)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/java.net.Socket.connect(Socket.java:558)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/java.net.URL.openStream(URL.java:1140)
        at org.primaresearch.io.xml.XmlValidator.getSchema(XmlValidator.java:53)
        at org.primaresearch.dla.page.io.xml.XmlPageWriter_Alto.run(XmlPageWriter_Alto.java:200)
        at org.primaresearch.dla.page.io.xml.XmlPageWriter_Alto.write(XmlPageWriter_Alto.java:115)
        at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:282)
        at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:161)
Could not initialise ALTO XML writer
java.lang.NullPointerException
        at org.primaresearch.dla.page.io.xml.XmlPageWriter_Alto.run(XmlPageWriter_Alto.java:200)
        at org.primaresearch.dla.page.io.xml.XmlPageWriter_Alto.write(XmlPageWriter_Alto.java:115)
        at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:282)
        at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:161)
14:38:23.306 ERROR ocrd-fileformat-transform - Transformation exited with return value 0 but no file was written.
~~~

Unfortunately with the network setup here, this also is a long wait for a connection error because packets are simply dropped... 

The preferred solution for me if ocr-fileformat would parse the somewhat standard `http_proxy` environment variable and passes the correct parameter to `java`:

~~~
java -Dhttp.proxyHost=http-proxy.sbb.spk-berlin.de -Dhttp.proxyPort=3128 [...other parameters...]
~~~

**Comment by mikegerber** [comment]
Found "the Java way of configuring the proxy": 
https://github.com/UB-Mannheim/ocr-fileformat/issues/133#issuecomment-801172931

**Comment by mikegerber** [comment]
Thinking about this, I see a related issue: AFAICS, ocrd_fileformat/ocr-fileformat (and also PAGE Viewer) need a network connection, apparently to load ALTO schemas, to convert to ALTO. I think this is not desirable.

@kba @bertsky What's your opinion on this?

**Comment by kba** [comment]
> @kba @bertsky What's your opinion on this?

I also dislike this. We had the same situation with the METS XSD validation in OCR-D/core and worked around it by [changing the schema](https://github.com/OCR-D/core/pull/531/commits/03a3fb6a7d7bbe8d1a15a73540509c45fbc0b418#diff-3cde48fa5fada837abb54bc314d92fadbf82a158b0f8e99723b06b91b196a533). It would be best if prima-core-libs had a mechanism to fall back to a local file if available before retrieving via network. Proxy settings and broken caching are just two things that can go wrong, there are more.

**Comment by bertsky** [comment]
I fully agree that none of these libraries should need networking to do their job in the first place, but don't grasp why changing the `schemaLocation` from a remote URL to a local file should be necessary for that. Isn't the library supposed to hold a copy of all the related XSDs? Since none of the involved schemas use versioning here, there's no need to fetch another copy. Better fix this upstream in prima-core-libs and prima-page-converter IMHO.

**Comment by kba** [comment]
> but don't grasp why changing the schemaLocation from a remote URL to a local file should be necessary for that. 

It's a workaround, not a solution, agreed. It depends on the XML library implementation. I seem to remember that the libxslt implementation in Perl e.g. had a mechanism where it would look for a schema with the same "basename" as the URL in either the working directory or the directory from where the importing schema was loaded. This is what we are emulating in core.

**Comment by mikegerber** [comment]
The PAGE schemas seem to be baked into the PrimaDla.jar:

~~~
% jar -tf PrimaDla.jar | grep schema
org/primaresearch/dla/page/io/xml/schema/
org/primaresearch/dla/page/io/xml/schema/2009-03-16_pagecontent.xsd
org/primaresearch/dla/page/io/xml/schema/2010-01-12_pagecontent.xsd
org/primaresearch/dla/page/io/xml/schema/2010-03-19_pagecontent.xsd
org/primaresearch/dla/page/io/xml/schema/2013-07-15_pagecontent.xsd
org/primaresearch/dla/page/io/xml/schema/2016-07-15_pagecontent.xsd
org/primaresearch/dla/page/io/xml/schema/2017-07-15_pagecontent.xsd
org/primaresearch/dla/page/io/xml/schema/2018-07-15_pagecontent.xsd
org/primaresearch/dla/page/io/xml/schema/2019-07-15_pagecontent.xsd
~~~
